spring.application.name=restful-service
spring.datasource.url=jdbc:postgresql://localhost:5432/product
spring.datasource.username=ethan
spring.datasource.password=ethan
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.mvc.view.suffix=.html
server.error.include-message=always
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false